spring.datasource.url=jdbc:postgresql://localhost:5432/order_service
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=admin
spring.datasource.password=admin

server.port=8090

client.service.url=http://localhost:8092/api/v1/clients
product.service.url=http://localhost:8093/api/v1/products
warehouse.service.url=http://localhost:8091/api/v1/warehouses/reserve