spring.datasource.url=jdbc:postgresql://localhost:5432/order_test
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=admin
spring.datasource.password=admin

server.port=8096

client.service.url=http://localhost:8099/api/v1/clients
product.service.url=http://localhost:8097/api/v1/products
warehouse.service.url=http://localhost:8098/api/v1/warehouses/reserve